- name: Itea
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Itea
      docker_container:
        name: itea
        image: dragonkoc/iteaapplication
        pull: true
        state: started
        ports:
          - "80:80"